sudo: required
services:
  - docker
script:
  - make image
deploy:
  provider: script
  script: bash .travis/docker_push.sh kubernetes-oom-event-generator xingse/kubernetes-oom-event-generator
  on:
    branch: master
